force-app/main/default/objects/Client__c/fields/Created_By_Admin__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to verify if Client was created by Admin</description>
    <label>Created By Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Legal_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Legal_Advisor__c</fullName>
    <label>Legal Advisor</label>
    <referenceTo>Legal_Advisor__c</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/Legal_Advisor__c.object-meta.xml
<CustomObject>
    <label>Legal Advisor</label>
    <nameField>
        <label>Legal Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>Account Name</description>
    <label>Account Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Advisor__c/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <description>Account Status</description>
    <label>Account Status</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ucl_legalAdvisorController.cls
public with sharing class ucl_legalAdvisorController {
    public ucl_legalAdvisorController() {

    }

    @AuraEnabled(Cacheable=true)
    public static Legal_Advisor__c[] getAllLegalAdvisors(){
        return [
            SELECT
                Id,
                Name,
                Account_Name__c,
                Account_Number__c,
                Account_Status__c,
                As_of_Date__c
            FROM Legal_Advisor__c
            WITH SECURITY_ENFORCED
            // ORDER BY Name
            // LIMIT 50
        ];
    }


    @AuraEnabled(Cacheable=true)
    public static Legal_Advisor__c[] searchLegalAdvisors(String searchTerm) {
        // Return all LegalAdvisors when no search term
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllLegalAdvisors();
        }
        // Prepare query paramters
        searchTerm = '%' + searchTerm + '%';
        // Execute search query
        return [
            SELECT
                Id,
                Name,
                Account_Name__c,
                Account_Number__c,
                Account_Status__c,
                As_of_Date__c
            FROM Legal_Advisor__c
            WHERE Name LIKE :searchTerm
            WITH SECURITY_ENFORCED
            // ORDER BY Name
            // LIMIT 50
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Client__c> getRelatedClients(Id advisorId) {
        return [
            SELECT 
                Id,
                Name,
                Client_Number__c,
                First_Name__c,
                Last_Name__c,
                Address__c,
                Phone__c,
                Created_By_Admin__c
            FROM Client__c
            WHERE Legal_Advisor__c = :advisorId
            WITH SECURITY_ENFORCED
       ];
    }


}